import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/global/Header";
import { UserProvider } from "@/app/context/UserContext";
import { Toaster} from 'sonner'

const poppins = Poppins({
  variable: "--font-poppins",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased relative`}>
        <UserProvider>
          <Header />
          {children}
        <Toaster position="top-center" richColors/>
        </UserProvider>
      </body>
    </html>
  );
}
