CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE food (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price FLOAT NOT NULL,
  category VARCHAR(50) NOT NULL,
)
CREATE TABLE `foodapp`.`foods` (`ID` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(50) NOT NULL , `price` FLOAT NOT NULL , `category` VARCHAR(255) NOT NULL DEFAULT 'others' , PRIMARY KEY (`ID`)) ENGINE = InnoDB;